-- Create table for Complementary Activities Catalog
-- Based on 'regulamento para atividades complementares.pdf'

CREATE TABLE IF NOT EXISTS complementary_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group" CHAR(1) NOT NULL, -- A, B, C, etc.
    code VARCHAR(5) NOT NULL, -- A1, H2, I1, etc.
    description TEXT NOT NULL,
    workload_formula TEXT, -- e.g., "10h por semestre"
    limit_hours INTEGER, -- e.g., 40
    requirements TEXT, -- Proven requirements
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Create an index on code for faster lookups
CREATE INDEX IF NOT EXISTS idx_complementary_activities_code ON complementary_activities (code);

-- Full Data Population from Regulation PDF
INSERT INTO complementary_activities ("group", code, description, workload_formula, limit_hours, requirements) VALUES
-- GRUPO A - Atividades de Iniciação à Docência, à Pesquisa ou à Extensão
('A', 'A1', 'Exercício de Monitoria ou Tutoria de atividades de ensino à distância, como bolsista, mediante Edital específico', '20 hs† / 40 hs‡ por semestre', 80, '- Declaração do prof. responsável'),
('A', 'A2', 'Iniciação Científica. Atuação como bolsista, mediante Edital específico', '20 hs† / 40 hs‡ por semestre', 80, '- Certificado do órgão de fomento ou declaração do orientador'),
('A', 'A3', 'Participação em pesquisas e projetos institucionais, outros projetos de pesquisa ou trabalho técnico, sob supervisão de professores do curso', '10 hs† / 20 hs‡ por semestre', 40, '- Declaração do prof. supervisor'),
('A', 'A4', 'Frequentar defesas de dissertação de mestrado e/ou tese de doutorado em área correlata ao curso', '02 hs por defesa', 20, '- Comprovante de participação'),
('A', 'A5', 'Frequentar apresentação de TCC do seu curso ou outro curso relacionado a área de computação', '05 hs por apresentação', 80, '- Comprovante de participação'),
('A', 'A6', 'Visitas técnicas em área de atuação do curso, coordenadas por professores do curso', 'até 02 hs por visita', 20, '- Comprovante de participação'),

-- GRUPO B - Participação em eventos
('B', 'B1', 'Palestras ou minicursos ministrados - específicos da área de atuação do curso na instituição', 'até 08 hs por atividade', 32, '- Certificado ou declaração da organização do evento'),
('B', 'B2', 'Participação externa em eventos, congressos, seminários, simpósios e conferências em áreas correlatas ao curso', 'até 08 hs por dia de participação', 40, '- Certificado ou declaração da organização do evento'),
('B', 'B3', 'Participação como competidor em competições científicas (maratonas de prog., robótica, etc) coord. por professores', 'até 08 hs por ativ. (+ 20 se 1º-3º lugar)', 80, '- Certificado ou declaração da organização do evento'),

-- GRUPO C - Atividades de Extensão
('C', 'C1', 'Participação em projetos ou atividades de extensão na área do curso, sob supervisão de professor do curso', '20 hs por projeto ou atividade', 80, '- Certificado ou declaração de participação'),
('C', 'C2', 'Participação em Curso de extensão na área do curso', 'até 08 hs', 20, '- Certificado ou declaração da organização do evento'),
('C', 'C3', 'Atividades de extensão oferecidas por outras instituições ou outros cursos', 'até 08 hs por atividade', 20, '- Certificado ou declaração da organização do evento'),

-- GRUPO D - Produção Técnica ou Científica
('D', 'D1', 'Publicação de trabalhos científicos em congressos ou simpósios - completo', 'até 15 hs por trabalho', 90, '- Cópia da publicação'),
('D', 'D2', 'Publicação de trabalhos científicos em congressos ou simpósios - resumo', 'até 05 hs por trabalho', 50, '- Cópia da publicação'),
('D', 'D3', 'Projeto de desenvolvimento de produto (Hardware ou Software)', 'até 20 hs por projeto', 40, '- Declaração do professor ou empregador'),
('D', 'D4', 'Publicação de trabalhos científicos em journal ou revista - com índice Qualis', '45 hs por trabalho', 90, '- Cópia da publicação'),

-- GRUPO E - Vivência profissional complementar
('E', 'E1', 'Realização de estágio não-curricular em Instituições conveniadas, Empresa Júnior ou Incubadora', '30 hs por semestre', 90, '- Termo de compromisso e Relatório de atividades'),
('E', 'E2', 'Atividade profissional específica na área correlata ao curso', 'até 15 hs por semestre', 90, '- Declaração do empregador (com CNPJ) ou Carteira de Trabalho'),
('E', 'E3', 'Atividade profissional específica em outras áreas', 'até 05 hs por semestre', 20, '- Declaração do empregador (com CNPJ) ou Carteira de Trabalho'),
('E', 'E4', 'Participação como titular ou suplente em entidade de representação estudantil específica', '05 hs por período (min 6 meses)', 15, '- Ata de eleição e Declaração de participação'),
('E', 'E5', 'Curso de aperfeiçoamento técnico', 'até 20 hs por curso', 80, '- Certificado ou declaração da entidade organizadora'),
('E', 'E6', 'Certificação específica', 'até 50 hs', 100, '- Certificado'),
('E', 'E7', 'Curso de língua estrangeira', '20% da carga horária', 50, '- Certificado ou Declaração de aprovação'),
('E', 'E8', 'Disciplinas de outros cursos ou instituições de ens. superior (não eletivas, pertinentes)', 'Carga da disciplina (até 20 hs/disc)', 30, '- Histórico Escolar Oficial ou declaração e Programa'),
('E', 'E9', 'Vivência de gestão ou representação de entidades relacionadas à área correlata do curso', 'até 25 hs por semestre', 50, '- Declaração ou Ata de posse/eleição'),

-- GRUPO F - Atividades de complementação da formação social, humana e cultural
('F', 'F1', 'Participação em projetos sociais ou atividades beneficentes', 'até 20 hs por semestre', 60, '- Declaração da coordenação do projeto'),
('F', 'F2', 'Participação como atleta ou organizador de atividades esportivas', 'até 02 hs por atividade', 40, '- Comprovante de participação'),
('F', 'F3', 'Participação como autor de trabalho cultural ou obra de cunho artístico em concursos, exposições, etc', 'até 05 hs por atividade', 40, '- Comprovante de participação'),
('F', 'F4', 'Participação em eventos de caráter cultural ou esportivo (competições, cinema, teatro, museu, etc)', '01 h por evento', 20, '- Tíquete ou comprovante de participação'),
('F', 'F5', 'Participação de intercâmbio ou convênio cultural', '20 hs por semestre', 40, '- Comprovante de participação'),

-- GRUPO G - Participação na Semana Acadêmica e de Extensão
('G', 'G1', 'Participação na "Semana de Engenharia de Computação" realizada pelo curso', 'Carga horária do certificado', 60, '- Certificado ou declaração da organização do evento'),
('G', 'G2', 'Semana de Extensão', 'Carga horária do certificado', 25, '- Certificado ou declaração da organização do evento'),
('G', 'G3', 'Participação na comissão organizadora da "Semana de Engenharia de Computação" realizada pelo curso', '10 hs por evento', 20, '- Certificado ou declaração da organização do evento'),

-- GRUPO H - Atividades Complementares Especiais (MIC)
('H', 'H1', 'Disciplina Optativa: Monitoria I, II, III ou IV (sem vínculo MIC)', '10 hs/semestre + Créditos disc.', 40, '- Aprovação na Disc. Monitoria; Relatório do Professor'),
('H', 'H2', 'Disciplina Optativa: Iniciação Científica I, II, III ou IV (com vínculo MIC)', '10 hs/semestre + Créditos disc.', 40, '- Aprovação na Disc. IC; Relatório do Orientador'),

-- GRUPO I - Atividades Complementares não enquadradas em outros grupos
('I', 'I1', 'Aceitação mediante critério da CAT, visando a correlação com os grupos anteriores', 'até 10 hs por semestre', 50, '- Observar a natureza da atividade');
