-- Create table for user comments
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    content TEXT NOT NULL CHECK (char_length(content) > 0),
    rating INT CHECK (rating >= 0 AND rating <= 5) DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- If table already exists, run this to add the column:
-- ALTER TABLE comments ADD COLUMN rating INT CHECK (rating >= 1 AND rating <= 5) DEFAULT 5;

-- Enable RLS
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read comments
CREATE POLICY "Public comments are viewable by everyone" 
ON comments FOR SELECT 
USING (true);

-- Allow authenticated users to insert comments
CREATE POLICY "Authenticated users can insert comments" 
ON comments FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');
