-- Create table for User's Complementary ActivCREATE TABLE IF NOT EXISTS user_complementary_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    activity_id BIGINT NOT NULL REFERENCES complementary_activities(id),
    
    description TEXT, -- Specific details (e.g., "Monitoria em Física I")
    hours NUMERIC(5, 2) NOT NULL CHECK (hours > 0), -- Hours claimed (allows decimals)
    semester VARCHAR(10) NOT NULL, -- e.g., "2024.1"
    document_link TEXT, -- URL to the proof document (Google Drive, Dropbox, etc.)
    
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints to prevent duplicates if needed, but likely allowed for different semesters
    CONSTRAINT fk_activity FOREIGN KEY (activity_id) REFERENCES complementary_activities(id)
);ities Submissions
-- Links users to activities from the catalog and stores proof/hours.



-- Enable RLS
ALTER TABLE user_complementary_activities ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own activities" 
ON user_complementary_activities FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own activities" 
ON user_complementary_activities FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own activities" 
ON user_complementary_activities FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own activities" 
ON user_complementary_activities FOR DELETE 
USING (auth.uid() = user_id);

-- Optional: Index for performance
CREATE INDEX IF NOT EXISTS idx_user_activities_user_id ON user_complementary_activities (user_id);
