-- ============================================================================
-- MASTER DATABASE SCHEMA
-- ============================================================================
-- Este arquivo consolida todas as tabelas, relações e funções do sistema.
-- Ele incorpora as melhorias de normalização, reduzindo os +20 scripts antigos 
-- para este único arquivo centralizado.
-- ============================================================================

-- 1. EXTENSÕES
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- 2. TABELAS PRINCIPAIS (Sem dependências fortes)
-- ============================================================================

CREATE TABLE IF NOT EXISTS universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS days (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS time_slots (
    id SERIAL PRIMARY KEY,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    course_id INT,
    CONSTRAINT chk_time_valid CHECK (start_time < end_time),
    CONSTRAINT uq_time_slot UNIQUE (start_time, end_time)
);

-- ============================================================================
-- 3. TABELAS DE DOMÍNIO (Cursos, Matérias, Usuários)
-- ============================================================================

CREATE TABLE IF NOT EXISTS periods (
    id SERIAL PRIMARY KEY,
    university_id INT NOT NULL,
    code TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    modalities TEXT,
    periods INT,
    campus TEXT,
    activies BOOLEAN,
    shift TEXT,
    workload INT,
    university_id BIGINT,
    needs_complementary_activities BOOLEAN
);

CREATE TABLE IF NOT EXISTS course_workloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT REFERENCES courses(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    min_credits INT,
    min_hours INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS course_credit_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    required_hours INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subject_categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subjects (
    id SERIAL PRIMARY KEY,
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    semester INT,
    name VARCHAR(150) NOT NULL,
    acronym TEXT,
    workload INT,
    category_id INT REFERENCES subject_categories(id) ON DELETE SET NULL,
    active BOOLEAN DEFAULT TRUE,
    optional BOOLEAN DEFAULT FALSE,
    has_practical BOOLEAN DEFAULT FALSE,
    has_theory BOOLEAN DEFAULT TRUE,
    elective BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS subject_requirements (
    id SERIAL PRIMARY KEY,
    subject_id INT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('SUBJECT', 'CREDITS')),
    prerequisite_subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,
    min_credits INT,
    CONSTRAINT chk_req_valid CHECK (
        (type = 'SUBJECT' AND prerequisite_subject_id IS NOT NULL AND min_credits IS NULL) OR
        (type = 'CREDITS' AND min_credits IS NOT NULL AND prerequisite_subject_id IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS subject_equivalencies (
    id SERIAL PRIMARY KEY,
    course_id INT REFERENCES courses(id) ON DELETE CASCADE,
    target_subject_id INT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    source_subject_id INT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subject_credits (
    subject_id INT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    credit_category_id BIGINT NOT NULL REFERENCES course_credit_categories(id) ON DELETE CASCADE,
    amount INT NOT NULL DEFAULT 0,
    PRIMARY KEY (subject_id, credit_category_id)
);

CREATE TABLE IF NOT EXISTS classes (
    subject_id INT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    day_id INT NOT NULL REFERENCES days(id),
    time_slot_id INT NOT NULL REFERENCES time_slots(id),
    class_code VARCHAR(50), 
    start_real_time TIME,
    end_real_time TIME,
    PRIMARY KEY (subject_id, day_id, time_slot_id)
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    is_paid BOOLEAN DEFAULT FALSE,
    subscription_expires_at TIMESTAMP WITH TIME ZONE,
    course_id INT REFERENCES courses(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 4. TABELAS DE ATIVIDADES E RELAÇÕES
-- ============================================================================

CREATE TABLE IF NOT EXISTS completed_subjects (
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject_id INT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, subject_id)
);

CREATE TABLE IF NOT EXISTS current_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    class_code TEXT, 
    semester TEXT,
    schedule_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS complementary_activity_groups (
    id CHAR(10) PRIMARY KEY,
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    max_hours INT NOT NULL,
    min_hours INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS complementary_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id CHAR(10) NOT NULL REFERENCES complementary_activity_groups(id), 
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    code VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    workload_formula TEXT,
    limit_hours INT,
    requirements TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_complementary_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_id BIGINT NOT NULL REFERENCES complementary_activities(id) ON DELETE CASCADE,
    description TEXT,
    hours NUMERIC(5,1),
    semester VARCHAR(20),
    document_link TEXT,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    rating INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    body TEXT,
    category TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id INT,
    action_type TEXT,
    action_value TEXT,
    banner_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    priority INT NOT NULL DEFAULT 0,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notification_reads (
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    notification_id INT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    read_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, notification_id)
);

-- ============================================================================
-- 5. FUNÇÕES DE AUTENTICAÇÃO E DEMAIS
-- (Movidas para o arquivo dedicado: database_functions.sql)
-- ============================================================================
