-- ============================================================================
-- SCRIPT DE CORREÇÃO DE TABELA (FIX SCHEMA)
-- ============================================================================
-- O erro "invalid input syntax for type uuid" acontece porque a tabela foi criada
-- esperando um ID do tipo UUID (padrão Supabase Auth), mas o seu sistema usa
-- IDs numéricos (ex: 1, 2, 3) da tabela 'users' customizada.
--
-- ESTE SCRIPT VAI:
-- 1. Remover a tabela errada.
-- 2. Criar a tabela correta aceitando números (BIGINT).
-- ============================================================================

-- 1. Remover a tabela antiga (se existir)
DROP TABLE IF EXISTS user_complementary_activities;

-- 2. Criar a tabela correta
CREATE TABLE user_complementary_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- CORREÇÃO: user_id agora é BIGINT (Número)
    user_id BIGINT NOT NULL,
    
    -- IMPORTANTE: activity_id com nome explícito "fk_activity" para o código funcionar
    activity_id BIGINT NOT NULL,
    
    hours NUMERIC(5,1) NOT NULL,
    semester VARCHAR(20) NOT NULL,
    description TEXT,
    document_link TEXT,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Chaves Estrangeiras
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity FOREIGN KEY (activity_id) REFERENCES complementary_activities(id) ON DELETE CASCADE
);

-- 3. Habilitar Segurança (RLS)
ALTER TABLE user_complementary_activities ENABLE ROW LEVEL SECURITY;

-- 4. Política de Acesso Público
CREATE POLICY "Public Access" ON user_complementary_activities FOR ALL USING (true);
