-- Physics Course Subjects (Course ID: 5)
-- Generated from CSV
-- Copy and paste this into Supabase SQL Editor

INSERT INTO subjects (
    course_id,
    semester,
    name,
    active,
    acronym,
    workload,
    category,
    optional,
    credits
)
VALUES
    (5, 1, 'Introdução às Ciências Experimentais', TRUE, '1A', 0, 'MANDATORY', false, ARRAY[1, 2, 0, 0]),
    (5, 1, 'Pensamento Computacional I', TRUE, '1B', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 1, 'Geometria Analítica I', TRUE, '1C', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 1, 'Cálculo I', TRUE, '1D', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 2, 'Mecânica Básica', TRUE, '2A', 0, 'MANDATORY', false, ARRAY[3, 1, 0, 0]),
    (5, 2, 'Pensamento Computacional II', TRUE, '2B', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 2, 'Cálculo II', TRUE, '2C', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 3, 'Mecânica', TRUE, '3A', 0, 'MANDATORY', false, ARRAY[3, 1, 0, 0]),
    (5, 3, 'Álgebra Linear', TRUE, '3B', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 3, 'Cálculo III', TRUE, '3C', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 4, 'Física Térmica', TRUE, '4A', 0, 'MANDATORY', false, ARRAY[3, 1, 0, 0]),
    (5, 4, 'Eletromagnetismo Básico', TRUE, '4B', 0, 'MANDATORY', false, ARRAY[3, 1, 0, 0]),
    (5, 4, 'Cálculo IV', TRUE, '4C', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 4, 'Projetos de Ensino de Física Térmica', TRUE, '4D', 0, 'MANDATORY', false, ARRAY[0, 0, 3, 0]),
    (5, 4, 'Sujeito Sociedade e Cultura', TRUE, '4E', 0, 'MANDATORY', false, ARRAY[2, 0, 0, 0]),
    (5, 5, 'Física Ondulatória e Óptica', TRUE, '5A', 0, 'MANDATORY', false, ARRAY[3, 1, 0, 0]),
    (5, 5, 'Eletromagnetismo', TRUE, '5B', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 5, 'Química Geral I', TRUE, '5C', 0, 'MANDATORY', false, ARRAY[3, 1, 0, 0]),
    (5, 5, 'Novas Tecnologias no Ensino de Física', TRUE, '5D', 0, 'MANDATORY', false, ARRAY[0, 0, 3, 0]),
    (5, 5, 'Prática Docente I', TRUE, '5E', 0, 'MANDATORY', false, ARRAY[0, 0, 0, 4]),
    (5, 5, 'Psicologia e Educação', TRUE, '5F', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 6, 'Relatividade', TRUE, '6A', 0, 'MANDATORY', false, ARRAY[2, 0, 0, 0]),
    (5, 6, 'Física Quântica', TRUE, '6B', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 6, 'Projetos de Ensino de Eletromag e Ondulatória', TRUE, '6C', 0, 'MANDATORY', false, ARRAY[0, 0, 3, 0]),
    (5, 6, 'História e Filosofia da Ciência', TRUE, '6D', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 6, 'Prática Docente II', TRUE, '6E', 0, 'MANDATORY', false, ARRAY[0, 0, 0, 4]),
    (5, 6, 'Educação em Ciências e Diversidade', TRUE, '6F', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 6, 'Libras e Educação Intercultural', TRUE, '6G', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 7, 'Física Moderna', TRUE, '7A', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 7, 'Epistemologia', TRUE, '7B', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 7, 'Projetos de Ensino de Física Moderna', TRUE, '7C', 0, 'MANDATORY', false, ARRAY[0, 0, 3, 0]),
    (5, 7, 'Prática Docente III', TRUE, '7D', 0, 'MANDATORY', false, ARRAY[0, 0, 0, 4]),
    (5, 7, 'Metodologia do Ensino de Física', TRUE, '7E', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 8, 'Física Estatística', TRUE, '8A', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 8, 'Introdução à Física do Estado Sólido', TRUE, '8B', 0, 'MANDATORY', false, ARRAY[4, 0, 0, 0]),
    (5, 8, 'Trabalho de Conclusão de Curso I', TRUE, '8C', 0, 'MANDATORY', false, ARRAY[2, 0, 0, 0]),
    (5, 8, 'Prática Docente IV', TRUE, '8D', 0, 'MANDATORY', false, ARRAY[0, 0, 0, 5]),
    (5, 8, 'Políticas Públicas e Organização da Ed. Básica', TRUE, '8E', 0, 'MANDATORY', false, ARRAY[3, 0, 0, 0]),
    (5, 8, 'Optativa I', TRUE, '8F', 0, 'ELECTIVE', true, ARRAY[4, 0, 0, 0]),
    (5, 9, 'Trabalho de Conclusão de Curso II', TRUE, '9A', 0, 'MANDATORY', false, ARRAY[2, 0, 0, 0]),
    (5, 9, 'Optativa II', TRUE, '9B', 0, 'ELECTIVE', true, ARRAY[4, 0, 0, 0]),
    (5, 9, 'Optativa III', TRUE, '9C', 0, 'ELECTIVE', true, ARRAY[4, 0, 0, 0]),
    (5, 9, 'Optativa IV', TRUE, '9D', 0, 'ELECTIVE', true, ARRAY[4, 0, 0, 0]);