-- Atualização de has_practical e has_theory

UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Administração e Org. Empresarial';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Geometria Analítica';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Introdução a Ciência da Computação';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Introdução à Engenharia';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Projeto de Interação';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Pré-Cálculo';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Lógica para Computação';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Introdução a Ciência da Computação - B';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Leitura e Produção de Textos';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Pré-Cálculo - B';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Introdução a Programação';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Cálculo a uma Variável';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Álgebra Linear';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Estruturas Discretas';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Introdução a Economia';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Mecânica Clássica';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Ética Profissional';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Introdução a Programação - B';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Algoritmos e Estruturas de Dados I';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Termodinâmica';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Software Básico';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Modelagem de Dados';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Cálculo a Várias Variáveis';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Introdução a Eng. Ambiental';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Humanidades e Ciências Sociais';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Banco de Dados';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Equações Diferenciais Ordinárias I';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Equações Diferenciais Ordinárias I - B';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Algoritmos e Estruturas de Dados II';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Arquitetura de Computadores';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Eletromagnetismo';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Redes de Computadores I';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Cálculo Numérico';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Circuitos Lineares';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Redes de Computadores II';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Programação Orientada a Objetos';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Probabilidade e Estatística';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Sistemas Operacionais';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Engenharia de Software';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Sinais e Sistemas';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Eletrônica Analógica';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Lab. de Circuitos Elétricos e Eletrônicos - B';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Linguagens Formais e Autômatos';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Lab. de Circuitos Elétricos e Eletrônicos - B';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Ondulatória e Física Moderna';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Análise de Algoritmos';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'História e Filosofia da Ciência';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Nanociência e Nanotecnologia';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Servidores de Redes';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Programação Linear';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Processamento Digital de Sinais';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Metodologia Científica';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Técnicas Digitais';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Libras I';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = '5G - Comunicação de Dados Móveis';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Infraestrutura de Redes para IoT';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Segurança de Redes II';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Sistemas Distribuídos';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Computação Gráfica';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Sistemas Inteligentes';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Sistemas de Controle';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Microcontroladores e Sistemas Embarcados';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Aprendizado Não Supervisionado';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'TCC I';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Computação de Alto Desempenho';
UPDATE subjects SET has_practical = 0,     has_theory = 0 WHERE name = 'Estágio Supervisionado';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'TCC II';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Animação Digital';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Ciência e Tecnologia dos Materiais';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Competições de Programação';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Desenho Técnico';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Fenômenos de Transporte';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Introdução à Mecânica dos Sólidos';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Introdução à Prog. para Dispositivos Móveis';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Mineração de Dados';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Organização do Trabalho e Normas';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Programação em Python';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Programação Orientada a Objetos usando C++';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Química Geral';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Redes de Transmissão';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Redes sem Fio';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Segurança de Redes de Computadores I';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Segurança de Redes de Computadores II';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Tópicos Complementares em Pré-Cálculo';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Tópicos em Algoritmos';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Tópicos Especiais em Computação Móvel';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Tópicos Especiais em Inteligência Artificial';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Tópicos Especiais em Otimização';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Tópicos Especiais em Programação';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Tópicos Especiais em Sistemas Digitais';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Virtualização de Servidores';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Visualização de Dados';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = '5G – Comunicação de Dados Móveis';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Monitoria I';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Monitoria II';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Monitoria III';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Monitoria IV';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Iniciação Científica I';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Iniciação Científica II';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Iniciação Científica III';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Iniciação Científica IV';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Algoritmos e Estruturas de Dados II - B';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Devops';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Tópicos Especiais em IA';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Internet VIa Satélite';
UPDATE subjects SET has_practical = 0,     has_theory = 0 WHERE name = 'Intro. Criptografia';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Educação e Sociedade';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Educação Financeira';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Geometria Euclidiana Plana';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Introdução à Lógica';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Introdução à Matemática';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Computação Algébrica';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Construções Geométricas e Geometria Métrica';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Funções';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Fundamentos Histórico-Filosóficos da Educação';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Matemática Financeira';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Oficina de Projetos de Ensino de Geometria';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Cálculo Diferencial e Integral I';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Introdução Às Ciências Experimentais';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Políticas Públicas e Formação de Professores';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Práticas Extensionistas';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Trigonometria e, Números Complexos';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Didática';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Mecânica Básica I';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Cálculo Diferencial e Integral II';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Oficina de Projetos de Ensino de Álgebra';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Língua Brasileira de Sinais';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'História da Matemática';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Prática Docente I';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Psicologia Aplicada à Educação';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Cálculo Diferencial e Integral III';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Mecânica Básica II';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Tendências em Educação Matemática';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Epistemologia';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Prática Docente II';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Oficina de Análise Combinatória, Probalidade e Estatística';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Estruturas Algébricas';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Metodologia da Pesquisa';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Cálculo Diferencial e Integral IV';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Novas Tecnologias Aplicadas Ao Ensino';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Projeto Final I';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Prática Docente III';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'História do Ensino da Matemática Escolar No Brasil';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Ciência e Meio Ambiente';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Sujeito, sociedade e, cultura';
UPDATE subjects SET has_practical = 0,     has_theory = 1 WHERE name = 'Projeto Final II';
UPDATE subjects SET has_practical = 1,     has_theory = 0 WHERE name = 'Prática Docente IV';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Ensino de Matemática em Modalidades Especiais';
UPDATE subjects SET has_practical = 1,     has_theory = 1 WHERE name = 'Oficina de Projetos de Ensino de Resolução de Problemas';