-- ====================================
-- POPULAR SUBJECTS.ACRONYM
-- ====================================

UPDATE subjects SET acronym = '1B' WHERE name = 'Administração e Org. Empresarial, Educação Financeira';
UPDATE subjects SET acronym = '1C' WHERE name = 'Geometria Analítica, Geometria Euclidiana Plana';
UPDATE subjects SET acronym = '1E' WHERE name = 'Introdução a Ciência da Computação, Introdução a Ciência da Computação - B, Introdução à Matemática';
UPDATE subjects SET acronym = '1A' WHERE name = 'Educação e Sociedade, Introdução à Engenharia';
UPDATE subjects SET acronym = '1G' WHERE name = 'Projeto de Interação';
UPDATE subjects SET acronym = '1D' WHERE name = 'Introdução à Lógica, Pré-Cálculo, Pré-Cálculo - B';
UPDATE subjects SET acronym = '1F' WHERE name = 'Lógica para Computação';
UPDATE subjects SET acronym = '1H' WHERE name = 'Leitura e Produção de Textos';
UPDATE subjects SET acronym = '2F' WHERE name = 'Introdução a Programação, Introdução a Programação - B, Matemática Financeira';
UPDATE subjects SET acronym = '2B' WHERE name = 'Construções Geométricas e Geometria Métrica, Cálculo a uma Variável';
UPDATE subjects SET acronym = '2C' WHERE name = 'Funções, Álgebra Linear';
UPDATE subjects SET acronym = '2E' WHERE name = 'Estruturas Discretas';
UPDATE subjects SET acronym = '2G' WHERE name = 'Introdução a Economia';
UPDATE subjects SET acronym = '2D' WHERE name = 'Fundamentos Histórico-Filosóficos da Educação, Mecânica Clássica';
UPDATE subjects SET acronym = '2A' WHERE name = 'Computação Algébrica, Ética Profissional';
UPDATE subjects SET acronym = '3E' WHERE name = 'Algoritmos e Estruturas de Dados I';
UPDATE subjects SET acronym = '3C' WHERE name = 'Introdução Às Ciências Experimentais, Termodinâmica';
UPDATE subjects SET acronym = '3D' WHERE name = 'Oficina de Projetos de Ensino de Geometria, Software Básico';
UPDATE subjects SET acronym = '3F' WHERE name = 'Modelagem de Dados, Práticas Extensionistas';
UPDATE subjects SET acronym = '3B' WHERE name = 'Cálculo Diferencial e Integral I, Cálculo a Várias Variáveis';
UPDATE subjects SET acronym = '3A' WHERE name = 'Introdução a Eng. Ambiental, Políticas Públicas e Formação de Professores';
UPDATE subjects SET acronym = '3G' WHERE name = 'Humanidades e Ciências Sociais, Trigonometria e, Números Complexos';
UPDATE subjects SET acronym = '4F' WHERE name = 'Banco de Dados';
UPDATE subjects SET acronym = '4A' WHERE name = 'Cálculo Diferencial e Integral II, Equações Diferenciais Ordinárias I, Equações Diferenciais Ordinárias I - B';
UPDATE subjects SET acronym = '4E' WHERE name = 'Algoritmos e Estruturas de Dados II, Algoritmos e Estruturas de Dados II - B, Oficina de Projetos de Ensino de Álgebra';
UPDATE subjects SET acronym = '4D' WHERE name = 'Arquitetura de Computadores, Mecânica Básica I';
UPDATE subjects SET acronym = '4B' WHERE name = 'Didática, Eletromagnetismo';
UPDATE subjects SET acronym = '4C' WHERE name = 'Língua Brasileira de Sinais, Redes de Computadores I';
UPDATE subjects SET acronym = '5E' WHERE name = 'Cálculo Numérico, Prática Docente I';
UPDATE subjects SET acronym = '5D' WHERE name = 'Circuitos Lineares, Mecânica Básica II';
UPDATE subjects SET acronym = '5C' WHERE name = 'Redes de Computadores II';
UPDATE subjects SET acronym = '5G' WHERE name = 'Programação Orientada a Objetos';
UPDATE subjects SET acronym = '5A' WHERE name = 'Cálculo Diferencial e Integral III, Probabilidade e Estatística';
UPDATE subjects SET acronym = '5B' WHERE name = 'História da Matemática, Sistemas Operacionais';
UPDATE subjects SET acronym = '5F' WHERE name = 'Engenharia de Software, Psicologia Aplicada à Educação';
UPDATE subjects SET acronym = '6A' WHERE name = 'Cálculo Diferencial e Integral IV, Sinais e Sistemas';
UPDATE subjects SET acronym = '6E' WHERE name = 'Eletrônica Analógica, Oficina de Análise Combinatória, Probalidade e Estatística';
UPDATE subjects SET acronym = '6D' WHERE name = 'Lab. de Circuitos Elétricos e Eletrônicos - B, Lab. de Circuitos Elétricos e Eletrônicos - B, Metodologia da Pesquisa';
UPDATE subjects SET acronym = '6F' WHERE name = 'Linguagens Formais e Autômatos, Prática Docente II';
UPDATE subjects SET acronym = '6B' WHERE name = 'Epistemologia, Ondulatória e Física Moderna';
UPDATE subjects SET acronym = '6G' WHERE name = 'Análise de Algoritmos, Tendências em Educação Matemática';
UPDATE subjects SET acronym = '32O' WHERE name = 'História e Filosofia da Ciência';
UPDATE subjects SET acronym = '12O' WHERE name = 'Nanociência e Nanotecnologia';
UPDATE subjects SET acronym = '6C' WHERE name = 'Estruturas Algébricas, Servidores de Redes';
UPDATE subjects SET acronym = '7B' WHERE name = 'História do Ensino da Matemática Escolar No Brasil, Programação Linear';
UPDATE subjects SET acronym = '7C' WHERE name = 'Processamento Digital de Sinais';
UPDATE subjects SET acronym = '7D' WHERE name = 'Metodologia Científica, Novas Tecnologias Aplicadas Ao Ensino';
UPDATE subjects SET acronym = '7A' WHERE name = 'Ciência e Meio Ambiente, Técnicas Digitais';
UPDATE subjects SET acronym = '10O' WHERE name = 'Libras I';
UPDATE subjects SET acronym = '13O' WHERE name = '5G - Comunicação de Dados Móveis, Organização do Trabalho e Normas';
UPDATE subjects SET acronym = '7O' WHERE name = 'Infraestrutura de Redes para IoT';
UPDATE subjects SET acronym = '5O' WHERE name = 'Desenho Técnico, Segurança de Redes II';
UPDATE subjects SET acronym = '8A' WHERE name = 'Ensino de Matemática em Modalidades Especiais, Sistemas Distribuídos';
UPDATE subjects SET acronym = '8D' WHERE name = 'Computação Gráfica, Prática Docente IV';
UPDATE subjects SET acronym = '8C' WHERE name = 'Sistemas Inteligentes';
UPDATE subjects SET acronym = '8E' WHERE name = 'Projeto Final II, Sistemas de Controle';
UPDATE subjects SET acronym = '8B' WHERE name = 'Microcontroladores e Sistemas Embarcados, Oficina de Projetos de Ensino de Resolução de Problemas';
UPDATE subjects SET acronym = '31O' WHERE name = 'Aprendizado Não Supervisionado';
UPDATE subjects SET acronym = '9B' WHERE name = 'TCC I';
UPDATE subjects SET acronym = '9A' WHERE name = 'Computação de Alto Desempenho';
UPDATE subjects SET acronym = '9C' WHERE name = 'Estágio Supervisionado';
UPDATE subjects SET acronym = '10A' WHERE name = 'TCC II';
UPDATE subjects SET acronym = '1O' WHERE name = 'Animação Digital';
UPDATE subjects SET acronym = '2O' WHERE name = 'Ciência e Tecnologia dos Materiais, Segurança de Redes de Computadores I';
UPDATE subjects SET acronym = '3O' WHERE name = 'Competições de Programação';
UPDATE subjects SET acronym = '6O' WHERE name = 'Fenômenos de Transporte';
UPDATE subjects SET acronym = '8O' WHERE name = 'Introdução à Mecânica dos Sólidos';
UPDATE subjects SET acronym = '9O' WHERE name = 'Introdução à Prog. para Dispositivos Móveis';
UPDATE subjects SET acronym = '11O' WHERE name = 'Mineração de Dados';
UPDATE subjects SET acronym = '14O' WHERE name = 'Programação em Python';
UPDATE subjects SET acronym = '15O' WHERE name = 'Programação Orientada a Objetos usando C++';
UPDATE subjects SET acronym = '16O' WHERE name = 'Química Geral';
UPDATE subjects SET acronym = '17O' WHERE name = 'Redes de Transmissão';
UPDATE subjects SET acronym = '18O' WHERE name = 'Redes sem Fio';
UPDATE subjects SET acronym = '20O' WHERE name = 'Segurança de Redes de Computadores II';
UPDATE subjects SET acronym = '21O' WHERE name = 'Tópicos Complementares em Pré-Cálculo';
UPDATE subjects SET acronym = '22O' WHERE name = 'Tópicos em Algoritmos';
UPDATE subjects SET acronym = '23O' WHERE name = 'Tópicos Especiais em Computação Móvel';
UPDATE subjects SET acronym = '24O' WHERE name = 'Tópicos Especiais em Inteligência Artificial';
UPDATE subjects SET acronym = '25O' WHERE name = 'Tópicos Especiais em Otimização';
UPDATE subjects SET acronym = '26O' WHERE name = 'Tópicos Especiais em Programação';
UPDATE subjects SET acronym = '27O' WHERE name = 'Tópicos Especiais em Sistemas Digitais';
UPDATE subjects SET acronym = '28O' WHERE name = 'Virtualização de Servidores';
UPDATE subjects SET acronym = '29O' WHERE name = 'Visualização de Dados';
UPDATE subjects SET acronym = '30O' WHERE name = '5G – Comunicação de Dados Móveis';
UPDATE subjects SET acronym = '33O' WHERE name = 'Monitoria I';
UPDATE subjects SET acronym = '34O' WHERE name = 'Monitoria II';
UPDATE subjects SET acronym = '35O' WHERE name = 'Monitoria III';
UPDATE subjects SET acronym = '36O' WHERE name = 'Monitoria IV';
UPDATE subjects SET acronym = '37O' WHERE name = 'Iniciação Científica I';
UPDATE subjects SET acronym = '38O' WHERE name = 'Iniciação Científica II';
UPDATE subjects SET acronym = '39O' WHERE name = 'Iniciação Científica III';
UPDATE subjects SET acronym = '40O' WHERE name = 'Iniciação Científica IV';
UPDATE subjects SET acronym = '90O' WHERE name = 'Devops';
UPDATE subjects SET acronym = '41O' WHERE name = 'Tópicos Especiais em IA';
UPDATE subjects SET acronym = 'nan' WHERE name = 'Internet VIa Satélite';
UPDATE subjects SET acronym = '4O' WHERE name = 'Intro. Criptografia';
UPDATE subjects SET acronym = '7F' WHERE name = 'Projeto Final I';
UPDATE subjects SET acronym = '7E' WHERE name = 'Prática Docente III';
UPDATE subjects SET acronym = '7G' WHERE name = 'Sujeito, sociedade e, cultura';