-- Migration: Create course_workloads table
CREATE TABLE IF NOT EXISTS course_workloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    -- 'obrigatórias', 'optativas', 'atividades complementares', 'eletivas'
    min_hours INTEGER DEFAULT 0,
    min_credits INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Insert initial data for Course ID 3 (Engenharia de Software)
-- Based on user's provided JSON
INSERT INTO course_workloads (course_id, type, min_hours, min_credits)
VALUES (3, 'obrigatórias', 3774, 198),
    (3, 'optativas', 360, 2),
    (3, 'atividades complementares', 210, 0),
    (3, 'eletivas', 360, 20) ON CONFLICT DO NOTHING;
-- Index for performance
CREATE INDEX IF NOT EXISTS idx_course_workloads_course_id ON course_workloads(course_id);