-- Migration: Add Universities and Course Configurations
-- 1. Create Universities Table
CREATE TABLE IF NOT EXISTS universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- 2. Add university_id to courses
ALTER TABLE courses
ADD COLUMN IF NOT EXISTS university_id BIGINT REFERENCES universities(id);
-- 3. Add needs_complementary_activities to courses
ALTER TABLE courses
ADD COLUMN IF NOT EXISTS needs_complementary_activities BOOLEAN DEFAULT FALSE;
-- 4. Add credit_categories to courses
ALTER TABLE courses
ADD COLUMN IF NOT EXISTS credit_categories JSONB DEFAULT '[]'::jsonb;
-- Comment on columns for clarity
COMMENT ON COLUMN courses.credit_categories IS 'Array of objects: [{"id": "theory", "name": "Teoria", "required_hours": 100}, ...]';
COMMENT ON COLUMN courses.needs_complementary_activities IS 'Whether students in this course need to complete complementary activities';